"use client";

import { useState } from "react";
import Image from "next/image";
import { contact, projects, services, type Service } from "./data";

type Page = "home" | "services" | "work" | "contact";

const Icon = ({ name, size = 24 }: { name: string; size?: number }) => {
  const paths: Record<string, React.ReactNode> = {
    whatsapp: <><path d="M20 11.5a8 8 0 0 1-11.8 7L4 20l1.5-4A8 8 0 1 1 20 11.5Z"/><path d="M8.5 8.2c.3-.7.6-.7.9-.7h.5c.2 0 .4.1.5.4l.7 1.6c.1.3 0 .5-.2.7l-.5.6c.4.8 1.1 1.5 2 1.9l.5-.6c.2-.2.4-.2.7-.1l1.5.7c.3.1.4.3.4.5v.5c0 .3-.1.6-.7.9-3 .8-6.3-2.4-5.5-5.4Z"/></>,
    menu: <><path d="M3 6h18M3 12h18M3 18h18"/></>, close: <><path d="m5 5 14 14M19 5 5 19"/></>, arrow: <path d="M5 12h14m-5-5 5 5-5 5"/>,
    mic: <><rect x="9" y="3" width="6" height="11" rx="3"/><path d="M6.5 11a5.5 5.5 0 0 0 11 0M12 17v4M8 21h8"/></>,
    sliders: <><path d="M5 4v16M12 4v16M19 4v16"/><path d="M3 8h4M10 15h4M17 10h4"/></>, wave: <path d="M3 13h4l2-8 4 15 3-10h5"/>,
    music: <><path d="M9 18V6l10-2v12"/><circle cx="6" cy="18" r="3"/><circle cx="16" cy="16" r="3"/></>,
    arrange: <><rect x="4" y="4" width="16" height="16" rx="1"/><path d="M12 4v16M4 10h8m0 4h8"/></>, scissors: <><circle cx="6" cy="7" r="3"/><circle cx="6" cy="17" r="3"/><path d="m8.5 8.5 10 10M8.5 15.5l10-10"/></>,
    file: <><path d="M6 3h8l4 4v14H6zM14 3v5h5M9 13h6m-6 4h6"/></>, keys: <><rect x="4" y="4" width="16" height="16" rx="1"/><path d="M7 4v10m3-10v10m4-10v10m3-10v10M4 14h16"/></>,
    home: <path d="m3 10 9-7 9 7v10h-6v-6H9v6H3z"/>, headphones: <path d="M4 14v-2a8 8 0 0 1 16 0v2M4 14v4h3v-5H4m16 2v4h-3v-5h3"/>, equalizer: <path d="M5 8v8m4-12v16m5-12v8m5-13v18"/>, mail: <><rect x="3" y="5" width="18" height="14" rx="1"/><path d="m3 7 9 6 9-6"/></>, instagram: <><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/></>, play: <path fill="currentColor" stroke="none" d="m9 6 9 6-9 6z"/>, external: <><path d="M14 4h6v6M20 4l-9 9"/><path d="M18 13v5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h5"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
};

const WhatsAppButton = ({ arrow = false }: { arrow?: boolean }) => <a className="whatsapp-btn" href={contact.whatsappUrl} target="_blank"><Icon name="whatsapp" size={19}/>Chat on WhatsApp{arrow && <Icon name="arrow" size={17}/>}</a>;
const SectionIntro = ({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) => <div className="intro"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><i/><p>{text}</p></div>;

export default function Site() {
  const [page, setPage] = useState<Page>("home");
  const [menu, setMenu] = useState(false);
  const go = (to: Page) => { setPage(to); setMenu(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  return <><Header page={page} go={go} openMenu={() => setMenu(true)}/>{page === "home" && <Home go={go}/>} {page === "services" && <Services/>} {page === "work" && <Work/>} {page === "contact" && <Contact/>}<Footer go={go}/>{menu && <MobileMenu close={() => setMenu(false)} go={go}/>}</>;
}

function Header({ page, go, openMenu }: { page: Page; go: (x: Page) => void; openMenu: () => void }) {
 return <header><button className="brand" onClick={() => go("home")}>THIRD EYE MUSIC</button><nav>{(["home", "services", "work", "contact"] as Page[]).map(x => <button className={page === x ? "active" : ""} onClick={() => go(x)} key={x}>{x === "home" ? "Home" : x[0].toUpperCase() + x.slice(1)}</button>)}</nav><div className="header-actions"><a className="header-whatsapp" href={contact.whatsappUrl}><Icon name="whatsapp" size={18}/>WhatsApp</a><button className="menu-btn" onClick={openMenu} aria-label="Open navigation"><Icon name="menu" size={31}/></button></div></header>
}

function Hero({ page }: { page: Page }) { const copy = page === "services" ? ["SERVICES", "What we do", "Professional music services to help bring your ideas to life."] : page === "work" ? ["OUR WORK", "Selected work", "A collection of music produced, recorded and crafted at Third Eye Music."] : ["CONTACT", "Have a project in mind?", "Let’s talk about your music. Reach out on WhatsApp or drop us an email. We’ll get back to you as soon as possible."]; return <section className={'inner-hero '+page}><SectionIntro eyebrow={copy[0]} title={copy[1]} text={copy[2]}/></section> }

function Home({ go }: { go: (x: Page) => void }) { return <main><section className="home-hero"><div><h1>THIRD EYE<br/>MUSIC</h1><i/><p>Music, recorded and<br/>produced with intention.</p><span>Recording　•　Music Production　•　Vocal Pitching</span><div className="hero-buttons"><WhatsAppButton/><button className="text-link" onClick={() => go("work")}>View our work <Icon name="arrow" size={18}/></button></div></div></section><section className="services-preview"><div className="section-heading"><div><span className="eyebrow">WHAT WE DO</span><h2>Services</h2></div><div><p>Explore our full range<br/>of services.</p><button className="text-link" onClick={() => go("services")}>View all services <Icon name="arrow" size={18}/></button></div></div><div className="service-cards">{services.slice(0,4).map(s => <ServiceCard key={s.title} s={s}/>)}</div></section><Studio/><Cta/></main> }
function ServiceCard({ s }: { s: Service }) { return <article className="service-card"><Icon name={s.icon} size={40}/><h3>{s.title}</h3><p>{s.description}</p></article> }
function Studio() { return <section className="studio"><div className="studio-head"><span className="eyebrow">OUR STUDIO</span><h2>Images &amp; Videos</h2><p>A glimpse of the space<br/>where ideas turn into music.</p></div><div className="gallery"><Image src="/e4953881-4c8f-459f-ae61-11c55f777240.png" alt="Music studio" width={600} height={400}/><Image src="/third-eye-music-recording-microphone.png" alt="Recording microphone" width={600} height={400}/><div className="video"><Image src="/third-eye-music-studio-wide.png" alt="Studio video preview" fill sizes="(max-width: 700px) 90vw, 900px"/><span><Icon name="play" size={32}/></span></div></div><button className="text-link studio-watch">Watch studio video <Icon name="arrow" size={18}/></button></section> }
function Services() { return <main><Hero page="services"/><section className="service-list">{services.map(s => <article key={s.number}><span>{s.number}</span><div className="service-icon"><Icon name={s.icon} size={29}/></div><h3>{s.title}</h3><p>{s.description}</p><Icon name="arrow" size={19}/></article>)}</section><Cta/></main> }
function Work() { return <main><Hero page="work"/><section className="work"><div className="tabs"><button className="active">All</button><button>YouTube</button><button>Spotify</button><span>More projects coming soon.</span></div><div className="projects">{projects.map((p) => <article className={'project '+p.platform.toLowerCase()} key={p.title}><div className="project-media"><Image src={p.image} alt="" fill sizes="(max-width: 700px) 42vw, 225px"/>{p.platform === "YouTube" && <span className="play"><Icon name="play" size={27}/></span>}{p.duration && <b>{p.duration}</b>}</div><div className="project-info"><h3>{p.title} <em>{p.platform}</em></h3><p>{p.artist}</p><p>Type of work:　{p.work}</p></div><button className="watch">{p.platform === "YouTube" ? "▰　Watch on YouTube" : "◉　 Listen on Spotify"}<Icon name="external" size={16}/></button></article>)}</div><p className="more">✦　More projects coming soon.</p></section><Cta/></main> }
function Contact() { return <main><Hero page="contact"/><section className="contact-cards"><ContactCard icon="whatsapp" title="WhatsApp"><strong>{contact.phone}</strong><WhatsAppButton arrow/></ContactCard><ContactCard icon="mail" title="Email"><p>{contact.email}<br/>or<br/>{contact.alternateEmail}</p></ContactCard><ContactCard icon="instagram" title="Instagram"><p>{contact.instagram}</p><a className="visit" href={contact.instagramUrl}>Visit Instagram <Icon name="external" size={16}/></a></ContactCard></section><div className="collaboration"><span><Icon name="equalizer"/></span><p>We&apos;re always open to new ideas and collaborations.<br/>Let&apos;s create something that connects.</p></div></main> }
function ContactCard({ icon, title, children }: { icon: string; title: string; children: React.ReactNode }) { return <article className="contact-card"><span><Icon name={icon} size={31}/></span><h2>{title}</h2>{children}</article> }
function Cta() { return <section className="cta"><div><h2>Have a project in mind?</h2><p>Let&apos;s create something great together.</p></div><WhatsAppButton/></section> }
function Footer({ go }: { go: (x: Page) => void }) { return <footer><div className="footer-top"><div><h3>THIRD EYE MUSIC</h3><p>A home studio focused on helping artists,<br/> singers and creators bring their ideas<br/> to life with clarity and purpose.</p></div><div className="footer-nav"><b>NAVIGATION</b>{(["home", "services", "work", "contact"] as Page[]).map(x => <button onClick={() => go(x)} key={x}>{x === "home" ? "Home" : x[0].toUpperCase()+x.slice(1)}</button>)}</div><div className="footer-connect"><b>CONNECT</b><a href={contact.whatsappUrl}><Icon name="whatsapp"/>WhatsApp</a><a href={'mailto:'+contact.email}><Icon name="mail"/>Email</a><a href={contact.instagramUrl}><Icon name="instagram"/>Instagram</a></div><div className="footer-details"><p><Icon name="whatsapp"/>{contact.phone}</p><p><Icon name="mail"/>{contact.email}<br/>or<br/>{contact.alternateEmail}</p><p><Icon name="instagram"/>{contact.instagram}</p></div></div><div className="footer-bottom">© Third Eye Music. All rights reserved.　 ·　 Recording　·　 Music Production　·　 Vocal Pitching</div></footer> }
function MobileMenu({ close, go }: { close: () => void; go: (x: Page) => void }) { const links: [Page,string,string][] = [["home","home","Home"],["services","headphones","Services"],["work","equalizer","Work"],["contact","mail","Contact"]]; return <div className="menu-overlay"><aside><div className="drawer-brand">THIRD EYE MUSIC <button onClick={close}><Icon name="close" size={35}/></button></div><div className="drawer-links">{links.map(([id,icon,label]) => <button key={id} onClick={() => go(id)}><Icon name={icon} size={34}/>{label}</button>)}</div><WhatsAppButton/><div className="drawer-contact"><span className="eyebrow">CONNECT</span><p><Icon name="whatsapp"/> {contact.phone}</p><p><Icon name="mail"/> {contact.email}<br/><span>or<br/>{contact.alternateEmail}</span></p><p><Icon name="instagram"/> {contact.instagram}</p></div><div className="drawer-bottom">© Third Eye Music. All rights reserved.<br/>Recording　•　Music Production　•　Vocal Pitching</div></aside><button aria-label="Close menu" onClick={close}/></div> }
